apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-dhjneymf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-dhjneymf:2b077a3249ebd18faf342d28dc4d2f214540c988@sha256:bbfa30c96422a14db1bc5883ebf669c86699e2ee427e1084bb788b91baa24836
          name: container-image
